<!DOCTYPE html>
<html>
<head>
    <title>Allocator.it</title>
</head>
<body>
    <div id="app">
        {{ message }}
        <button-counter></button-counter>
    </div>

    <link rel="stylesheet" href="/assets/css/min/styles.css" />
    <link rel="stylesheet" href="/assets/css/min/global.css" />
    <script src="https://cdn.jsdelivr.net/npm/vue@2.6.12"></script>
    <script src="/assets/js/min/main.js"></script>
</body>
</html>
